
namespacesMandatoryMtls: 
  - name: databases
  - name: applications

svc:
  - name: apigateway
    namespace: applications
    docker_image: ghcr.io/ac-4/xcexample.apigateway:latest
    replicas: 1
    port: 80
    host : "*"
    apiPrefix: "/status"
    customServiceAccount: true
    customServiceAccountName: "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
    virtualServiceEnabled: true

  - name: weather
    namespace: applications
    docker_image: ghcr.io/ac-4/xcexample.api.weather:latest
    replicas: 1
    port: 80
    host : "*"
    apiPrefix: "/"
    customServiceAccount: false
    whitelistedServiceName: "apigateway"
    whitelistedServiceNameSpace: "applications"

  - name: sometext
    namespace: applications
    docker_image: ghcr.io/ac-4/xcexample.api.sometext:latest 
    replicas: 1
    port: 80
    host : "*"
    apiPrefix: "/"
    customServiceAccount: false
    whitelistedServiceName: "apigateway"
    whitelistedServiceNameSpace: "applications"